name: Unit Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies 
        working-directory: ./unit
        run: npm i
      - name: Run unit tests with coverage
        working-directory: ./unit
        run: npm run test:coverage
      - uses: actions/upload-artifact@v2
        with:
          name: coverage - ${{ matrix.node-version }}
          path: ./unit/coverage

  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:ci
          working-directory: e2e
      - name: store screenshots if tests fail
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: ./e2e/cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: store screenshots if tests fail
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: ./e2e/cypress/videos